#!/usr/local/bin/python
# Program test0.py for tensorflow check
print ("Test program to check tensorflow test0.py ")

import numpy as nm
import pandas as pd
import scipy as sc
import matplotlib.pyplot as plt


print ("imported numpy(nm), pandas(pd), scipy(sc) ")
import tensorflow as tf
print ("imported tensorflow(tf)")

# Code introduced on Nov/11/2021 Thu
print ("New Code Nov/11/2021 Thu")

c = tf.constant("Hello World!!")
with tf.Session() as sess:
       print (sess.run(c))

# Create a graph
g = tf.Graph()

# Establish Graph as the default graph
with g.as_default():
    # Assemble a graph consisting of the following 3 operands
    #  * Two tf.constant operation to create the operands
    #  * One tf.add operation to add the two operands
    x = tf.constant(8, name="x_const")
    y = tf.constant(5, name="y_const")
    my_sum = tf.add(x, y, name="x_y_sum")

    # Now create s session
    # The session will run the default graph
    with tf.Session() as sess:
        print (my_sum.eval())

print (" end of pgm test0.py for imports ")
print (" added extra line to enhance s/w characteristics -- Starwars")
print (" added another line for Luke Skywalker ")
print (" added another line for Darth Vader, even though he no longer exists in Nov 2020")
print (" added another line for Kylo Ren, maybe he is conflicted - eval done on Nov/11/2021")
print (" May/05/2022 added new branch for CS02 Spring 2022") 
print (" May/05/2022 16:00 hrs - Added New Spiderman to the ecosystem" )
print (" May/05/2022 16:03 hrs - What about Wanda Vision ? ")
print (" May/05/2022 16:10 hrs - Need to include Dr. Strange! ")  
print (" May/05/2022 21:03 hrs - Dr. Strange cannot be included as DorMamu forbade it ")
